version: '3.4'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=flowable
      - POSTGRES_USER=flowable
      - POSTGRES_DB=flowable
    ports:
      - 15433:5432
    networks:
      - flow-app
#  db:
#    image: mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=flowable
#      - MYSQL_USER=flowable
#      - MYSQL_PASSWORD=flowable
#    networks:
#      - flow-app
#    ports:
#      - 13306:3306

  flowable-idm:
    image: flowable/flowable-idm:latest
#    build: ./flowable-idm
    environment:
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flowable
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flowable?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_IDM_APP_ADMIN_USER_ID=admin
      - FLOWABLE_IDM_APP_ADMIN_PASSWORD=test
      - FLOWABLE_IDM_APP_ADMIN_FIRST_NAME=UI
      - FLOWABLE_IDM_APP_ADMIN_LAST-NAME=Admin
      - FLOWABLE_REST_APP_ADMIN_USER_ID=rest-admin
      - FLOWABLE_REST_APP_ADMIN_PASSWORD=test
      - FLOWABLE_REST_APP_ADMIN_FIRST_NAME=Rest
      - FLOWABLE_REST_APP_ADMIN_LAST-NAME=Admin
    networks:
      - flow-app
    ports:
      - 18888:8080
    depends_on:
      - db
    entrypoint: ["./wait-for-something.sh", "db", "5432", "Database", "java", "-jar", "/app.war"]
#    entrypoint: ["./wait-for-something.sh", "db", "3306", "Database", "catalina.sh", "run"]

  flowable-admin:
    image: flowable/flowable-admin:latest
#    build: ./flowable-admin
    environment:
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flowable
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flowable?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM_URL=http://flowable-idm:8080/
      - FLOWABLE_COMMON_APP_IDM_REDIRECT_URL=http://localhost:18888/
      - FLOWABLE_COMMON_APP_IDM_ADMIN_USER=admin
      - FLOWABLE_COMMON_APP_IDM_ADMIN_PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_PROCESS_SERVER_ADDRESS=http://flowable-boot-app
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_PROCESS_PORT=8080
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_PROCESS_CONTEXT_ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_PROCESS_REST_ROOT=process-api
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_PROCESS_USER_NAME=admin
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_PROCESS_PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CMMN_SERVER_ADDRESS=http://flowable-boot-app
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CMMN_PORT=8080
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CMMN_CONTEXT_ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CMMN_REST_ROOT=cmmn-api
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CMMN_USER_NAME=admin
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CMMN_PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_APP_SERVER_ADDRESS=http://flowable-boot-app
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_APP_PORT=8080
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_APP_CONTEXT_ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_APP_REST_ROOT=app-api
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_APP_USER_NAME=admin
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_APP_PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_DMN_SERVER_ADDRESS=http://flowable-boot-app
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_DMN_PORT=8080
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_DMN_CONTEXT_ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_DMN_REST_ROOT=dmn-api
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_DMN_USER_NAME=admin
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_DMN_PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_FORM_SERVER_ADDRESS=http://flowable-boot-app
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_FORM_PORT=8080
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_FORM_CONTEXT_ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_FORM_REST_ROOT=form-api
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_FORM_USER_NAME=admin
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_FORM_PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CONTENT_SERVER_ADDRESS=http://flowable-boot-app
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CONTENT_PORT=8080
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CONTENT_CONTEXT_ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CONTENT_REST_ROOT=content-api
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CONTENT_USER_NAME=admin
      - FLOWABLE_ADMIN_APP_SERVER_CONFIG_CONTENT_PASSWORD=test
    networks:
      - flow-app
    ports:
      - 19988:8080
    depends_on:
      - db
      - flowable-idm
    entrypoint: ["./wait-for-something.sh", "db", "5432", "Database", "java", "-jar", "/app.war"]
#    entrypoint: ["./wait-for-something.sh", "db", "3306", "Database", "catalina.sh", "run"]


  flowable-modeler:
    image: flowable/flowable-modeler:latest
#    build: ./flowable-modeler
    environment:
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flowable
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flowable?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM_URL=http://flowable-idm:8080/
      - FLOWABLE_COMMON_APP_IDM_REDIRECT_URL=http://localhost:18888/
      - FLOWABLE_COMMON_APP_IDM_ADMIN_USER=admin
      - FLOWABLE_COMMON_APP_IDM_ADMIN_PASSWORD=test
      - FLOWABLE_MODELER_APP_DEPLOYMENT_API_URL=http://flowable-boot-app:8080/app-api
    networks:
      - flow-app
    ports:
      - 18088:8080
    depends_on:
      - db
      - flowable-idm
    entrypoint: ["./wait-for-something.sh", "db", "5432", "Database", "java", "-jar", "/app.war"]
#    entrypoint: ["./wait-for-something.sh", "db", "3306", "Database", "catalina.sh", "run"]

  flowable-task:
    image: flowable/flowable-task:latest
#    build: ./flowable-modeler
    environment:
      - SERVER_PORT=8080
#      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flowable
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flowable?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM_URL=http://flowable-idm:8080/
      - FLOWABLE_COMMON_APP_IDM_REDIRECT_URL=http://localhost:18888/
      - FLOWABLE_COMMON_APP_IDM_ADMIN_USER=admin
      - FLOWABLE_COMMON_APP_IDM_ADMIN_PASSWORD=test
    networks:
      - flow-app
    ports:
      - 18181:8080
    depends_on:
      - db
      - flowable-idm
    entrypoint: ["./wait-for-something.sh", "db", "5432", "Database", "java", "-jar", "/app.war"]
#    entrypoint: ["./wait-for-something.sh", "db", "3306", "Database", "catalina.sh", "run"]

  flowable-boot-app:
    build: ./flowable-boot-app
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flowable
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flowable?characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM_URL=http://flowable-idm:8080/
      - FLOWABLE_COMMON_APP_IDM_ADMIN_USER=admin
      - FLOWABLE_COMMON_APP_IDM_ADMIN_PASSWORD=test
    networks:
      - flow-app
    ports:
      - 18080:8080
    depends_on:
      - db
      - flowable-idm
    entrypoint: ["./wait-for-something.sh", "db", "5432", "Database", "java", "-jar", "/app.jar"]
#    entrypoint: ["./wait-for-something.sh", "db", "3306", "Database", "java", "-jar", "/app.jar"]

networks:
  flow-app: